package me.mudkip.moememos.ui.theme

import androidx.compose.ui.graphics.Color

// Telos 纸白（light）：冷中性纸面 + 墨色字，slate 蓝灰强调
val md_theme_light_primary = Color(0xFF5D6B78)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDEE3E8)
val md_theme_light_onPrimaryContainer = Color(0xFF19232C)
val md_theme_light_secondary = Color(0xFF5F6975)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE4E6EA)
val md_theme_light_onSecondaryContainer = Color(0xFF1D2228)
val md_theme_light_tertiary = Color(0xFF6F8F4E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDFE8D2)
val md_theme_light_onTertiaryContainer = Color(0xFF223012)
val md_theme_light_error = Color(0xFFC0503E)
val md_theme_light_errorContainer = Color(0xFFF6DAD4)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF44140C)
val md_theme_light_background = Color(0xFFEEF0F2)
val md_theme_light_onBackground = Color(0xFF21252B)
val md_theme_light_surface = Color(0xFFEEF0F2)
val md_theme_light_onSurface = Color(0xFF21252B)
val md_theme_light_surfaceVariant = Color(0xFFE4E6EA)
val md_theme_light_onSurfaceVariant = Color(0xFF565D66)
val md_theme_light_outline = Color(0xFFA9AFB8)
val md_theme_light_outlineVariant = Color(0xFFDCDFE3)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F3)
val md_theme_light_inverseSurface = Color(0xFF2E3237)
val md_theme_light_inversePrimary = Color(0xFFAEBBC8)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF5D6B78)
val md_theme_light_surfaceDim = Color(0xFFD5D8DD)
val md_theme_light_surfaceBright = Color(0xFFFBFBFC)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFFBFBFC)
val md_theme_light_surfaceContainer = Color(0xFFF2F3F5)
val md_theme_light_surfaceContainerHigh = Color(0xFFE9EBEE)
val md_theme_light_surfaceContainerHighest = Color(0xFFE4E6EA)

// Telos 夜间（dark）
val md_theme_dark_primary = Color(0xFFAEBBC8)
val md_theme_dark_onPrimary = Color(0xFF232B33)
val md_theme_dark_primaryContainer = Color(0xFF3C4650)
val md_theme_dark_onPrimaryContainer = Color(0xFFDCE3EA)
val md_theme_dark_secondary = Color(0xFF9098A1)
val md_theme_dark_onSecondary = Color(0xFF22262C)
val md_theme_dark_secondaryContainer = Color(0xFF2A2E34)
val md_theme_dark_onSecondaryContainer = Color(0xFFE1E4E8)
val md_theme_dark_tertiary = Color(0xFFA3BC85)
val md_theme_dark_onTertiary = Color(0xFF1F2B10)
val md_theme_dark_tertiaryContainer = Color(0xFF3A4A2C)
val md_theme_dark_onTertiaryContainer = Color(0xFFDCE7CB)
val md_theme_dark_error = Color(0xFFE89A8B)
val md_theme_dark_errorContainer = Color(0xFF7A2E20)
val md_theme_dark_onError = Color(0xFF3F120A)
val md_theme_dark_onErrorContainer = Color(0xFFFBDCD5)
val md_theme_dark_background = Color(0xFF15171A)
val md_theme_dark_onBackground = Color(0xFFE7E9EC)
val md_theme_dark_surface = Color(0xFF15171A)
val md_theme_dark_onSurface = Color(0xFFE7E9EC)
val md_theme_dark_surfaceVariant = Color(0xFF26292E)
val md_theme_dark_onSurfaceVariant = Color(0xFF9098A1)
val md_theme_dark_outline = Color(0xFF545B63)
val md_theme_dark_outlineVariant = Color(0xFF31353B)
val md_theme_dark_inverseOnSurface = Color(0xFF21252B)
val md_theme_dark_inverseSurface = Color(0xFFE7E9EC)
val md_theme_dark_inversePrimary = Color(0xFF5D6B78)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFAEBBC8)
val md_theme_dark_surfaceDim = Color(0xFF15171A)
val md_theme_dark_surfaceBright = Color(0xFF33373D)
val md_theme_dark_surfaceContainerLowest = Color(0xFF101214)
val md_theme_dark_surfaceContainerLow = Color(0xFF1E2024)
val md_theme_dark_surfaceContainer = Color(0xFF23262B)
val md_theme_dark_surfaceContainerHigh = Color(0xFF26292E)
val md_theme_dark_surfaceContainerHighest = Color(0xFF2D3138)


val seed = Color(0xFF5D6B78)
